### ISSUE TITLE
VIDEOJS: WARN: Player x is already initialised. Options will not be applied.

### ISSUE THREAD

**Issue by gwidaz** [collab-project/videojs-wavesurfer#10] opened 2015-10-07 12:44 UTC
Hey everyone, first of all I want to thank for this awesome player! I made a really nice skin to look nice for my website, but.. I been having issues with design elements and couple of errors which I hope some of you can help me with that.

I use Gridder v1.4 for my videos to appear once the image is clicked, and they are working just fine, I can play the video etc, but once I close and reopen the same video I get this error:

         VIDEOJS: WARN: Player "(my unique id)" is already initialised. Options will not be applied.

and then all of the design disapears from the player.. 

Plus I have this error for each video I output on the website:

         Uncaught TypeError: The element or ID supplied is not valid. (videojs)

I tryed to fix it using code which I found on other topis regarding this, but It did not work.

You can see all working website at:   www.xxxtu.be (NOTE : this is an adult website!)

Any help will be appreciated! 

This code is used for the gridder and placed in a very bottom of the page:

        <script>
            jQuery(document).ready(function ($) {
                $(".gridder").gridderExpander({
                    scroll: true,
                    scrollOffset: 60,
                    scrollTo: "panel", // panel or listitem
                    animationSpeed: 400,
                    animationEasing: "easeInOutExpo",
                    showNav: true,
                    closeText: "Close",
                });
            });
        </script>

And this is code to call the player:

       <div id="gridder-content-'.$row['id'].'" class="gridder-content">
              <div class="player">
              <script type="text/javascript">
                   videojs("my_video_'.$row['id'].'").ready(function(){});
               </script>
               <video id="my_video_'.$row['id'].'" class="video-js vjs-default-skin" width="1197px" height="673px" controls preload="none" poster="upl/cover/video/'.$row['image'].'">
                <source src="v/'.$row['url'].'" type="video/mp4" />
                 </video>
               </div>
          </div>

Which is abowe the gridder code.

**Comment by thijstriemstra** [comment] 2015-10-08 16:27
You need to call `player.waveform.destroy()` before you create a new player instance to prevent this error.

**Comment by gwidaz** [comment] 2015-10-08 17:05
Well I did managed to fix it by using code from docs again for some reason:

    videojs(document.getElementById("my_video_'.$row['id'].'"), {}, function() {
                             
    });

but I am still not getting this error to disappear

    Uncaught TypeError: The element or ID supplied is not valid. (videojs)

**Comment by thijstriemstra** [comment] 2015-10-08 17:08
It's a really weird ID isn't it? `my_video_'.$row['id'].'` If this is evaluated by the library you're using then you probably shouldn't hardcode the html elements but create the video.js player using javascript/that library. Closing this since it doesn't look related to this plugin anymore. Feel free to re-open with an example that can reproduce an error (without any third-party libraries used).

**Closed by thijstriemstra** 2015-10-08 17:08 UTC
Labels: question

**Comment by hersche** [comment] 2018-05-14 06:05
Hello, i have the same issue out of other reasons i think..

html-part:

`        <audio controls class="center-block video-js vjs-default-skin "  id="mainAudio" poster="<?php echo $poster; ?>">
        </audio>`

JS:

` player = videojs('mainAudio', {
    controls: true,
    autoplay: true,
    fluid: false,
    loop: false,
    width: 600,
    height: 300,
    plugins: {
        wavesurfer: {
            src: '<?php echo $global['webSiteRootURL'] . "videos/" . $video['filename'].$ext; ?>',
            msDisplayMax: 10,
            debug: true,
            waveColor: 'grey',
            progressColor: 'black',
            cursorColor: 'black',
            hideScrollbar: true
        }
    }
}, function(){
    // print version information at startup
    videojs.log('Using video.js', videojs.VERSION,
        'with videojs-wavesurfer', videojs.getPluginVersion('wavesurfer'));
});

// error handling
player.on('error', function(error) {
    console.warn('ERROR:', error);
});`

you can see it in action here: https://demo.codebea.ch/video/dot-05-imf
and in original file here: https://github.com/hersche/YouPHPTube/blob/85ef8e037b05aba13f76a934a183cc011f6efdf8/view/include/audio.php

your code in the demo gets combined with other's and minified (if you wonder where it is)

the very weird thing: it works on localhost! absolutly nice.. makes no sense with JS, i'm confused..

also a offtopic-question: is the plugin downloading the audio first completly (before play)? am i right with this? i think it have to be, because it has to visualize the whole file.. that would be very cool as "progress"-visualize, so play and draw while downloading.. but i don't know how difficult that is.

thanks anyway for your work! :+1:

**Comment by KENYHU** [comment] 2019-04-02 11:22
Hi man,  you can do like this:

> var player;
> if( player == undefind ) {
>    player = videojs('xxxx_div', {});        //if videojs player don't exists, you can create one
> } else {
>    $("#video_div").attr('src', source);  //change video source 
>    player.load();                                     //reload videoJS
> }
