### ISSUE TITLE
CPU-Usage

### ISSUE THREAD

**Issue by hersche** [collab-project/videojs-wavesurfer#62] opened 2018-05-17 18:42 UTC
## Description
High CPU-Usage.

## Steps to reproduce
Activate and use the plugin.

### Expected
I except, that after create the visualisation, the cpu-usage is reduced

### Actual
While play, about 100% (on one core), about 50-60% withouth wavesurfer.

## Additional Information
Please include any additional information necessary here. Including the following:
#### videojs/wavesurfer
6.7.3
#### browsers
i personal use firefox...
#### OSes
... with kali and kubuntu

**Comment by thijstriemstra** [comment] 2018-05-17 18:54
@hersche can you re-recreate this with a pure video.js example? or a pure wavesurfer.js example?

**Comment by hersche** [comment] 2018-05-17 23:25
i have made a fork and found, that in the original demo-"hal.wav", setCurrentTime is called 1391 times in about 8 seconds. well, that can be nice for playing or fluid animations, but it's a bit intensive..

i have changed it that, mostly on progress, it only do the update every 50 time (can be decreased).

with this, it does update 62 times only, but has no visual impact (as i see, but it's still several times in a second).

also i have added it to the finish-play; this caused a incorrect result anyway, adding this should be just proper..

it's a bit ugly, but to force a update on events, i set the counter to 50.

https://github.com/hersche/videojs-wavesurfer/commit/cd7e22f7a8408cbd5365561f944be9c382dd59e9

tell me, when i should do a PR.

**Comment by thijstriemstra** [comment] 2018-05-21 20:29
@hersche this sounds great, can you make a PR?

**Comment by thijstriemstra** [comment] 2018-05-21 20:32
> // emit the timeupdate event so that the tech knows about the time change
> this.trigger('timeupdate');

I wasn't even aware this was in there, related to #60. I would like to get rid of that line as well.

**Comment by hersche** [comment] 2018-05-21 21:03
i'm not shure, what this line does, because that's my first mod on videojs-libs at all..
but i make the PR quickly :)

**Comment by thijstriemstra** [comment] 2018-05-22 22:51
@hersche can you comment out this line (disable the custom tech) https://github.com/collab-project/videojs-wavesurfer/blob/master/src/js/videojs.wavesurfer.js#L770 and any other tech-related lines (like https://github.com/collab-project/videojs-wavesurfer/blob/master/src/js/videojs.wavesurfer.js#L75) and see if this improves things? Also comment out the `this.trigger('timeupdate');` line.

**Comment by thijstriemstra** [comment] 2018-05-22 23:34
@hersche yea you should just:

Do once:

- checkout code
- npm install
- npm run build
- npm run start

And you can now make changes and it should automatically rebuild.

**Comment by hersche** [comment] 2018-05-22 23:48
ok, i did the test with the 44mb wav-file again and it did not raise the cpu.. as i removed my code, this seems to be a working solution..

**Comment by thijstriemstra** [comment] 2018-05-22 23:53
@hersche that's good news and fucked up at the same time. Looks like this is a duplicate of #60 :-/

**Comment by hersche** [comment] 2018-05-23 00:14
well, then i let my workaround stay for the moment and wait until #60 is closed.. 

thanks for help me testing there, but about the tech-stuff from videojs, i have no clue..

**Comment by thijstriemstra** [comment] 2018-05-23 00:18
@hersche can you paste a `git diff` of your workaround here?

**Comment by thijstriemstra** [comment] 2018-05-23 00:25
Can you try a clean version without any of your changes, just disabling the tech basically, and see if that fixes it? I'd rather not introduce extra code if it's not needed.

**Comment by hersche** [comment] 2018-05-23 00:33
i did this already for the test. i removed my counter, run the test (passing), commented out, what you said, failed on the test, tried it with the 44mb file, you said, it's same like #60 and i decide to stay on my counter-solution then.. i have it right now changed this way, i can commit it, you can reopen the PR and accept it withouth the counter. 

but you found the solution with commenting out, so why not simply do a commit like this? i did nothing more than the counter, which i should remove completly and the rest is your work.

for youphptube, i let the counter-workaround enabled for now, because it's working.

**Comment by thijstriemstra** [comment] 2018-05-23 00:35
> for youphptube, i let the counter-workaround enabled for now, because it's working.

I'm just trying to figure out if your counter-workaround is necessary in videojs-wavesurfer in order to fix it in your opionion, but it sounds like it is and you're using it for now until a new videojs-wavesurfer is released without the counter-workaround but with a tech fix.

**Comment by thijstriemstra** [comment] 2018-05-23 00:38
> i have it right now changed this way, i can commit it, you can reopen the PR and accept it withouth the counter.

I'll re-open the PR but can't guarantee I'll merge it but it's a good way to show your ideas using code.

**Comment by hersche** [comment] 2018-05-23 00:48
mmh, but when i comment out, what you told me (i would do nothing else, it's only your idea then, as my commit, but well..), then a problem (i already checked this) is, that it will fail with the tests (which are needed to merge anyway). so i have to remove some tests, what should be the last solution.. 

i mean, make that sense? for me, it's just ok to close the issue and the PR, and wait until a real solution is done. sorry for my weirdness, i was not aware of travis and co.

and my counter-solution definently is no final solution. with the failing tests not even a temporary for the official repo i think.. but for my use, it does the trick.

**Comment by thijstriemstra** [comment] 2018-05-23 00:50
> then a problem (i already checked this) is, that it will fail with the tests (which are needed to merge anyway). so i have to remove some tests, what should be the last solution..

You mean the unit tests of videojs-wavesurfer right?

**Comment by hersche** [comment] 2018-05-23 00:53
yes

**Comment by thijstriemstra** [comment] 2018-05-23 00:56
@hersche you can delete, or move, `test/tech.spec.js` temporarily if you disabled the registration of the tech. That should fix the tests.

**Comment by hersche** [comment] 2018-05-23 00:58
ok

**Comment by thijstriemstra** [comment] 2018-06-03 21:35
@hersche should be fixed in 2.3.1.

**Closed** 2018-06-03 21:34 UTC
Labels: bug
